### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ghost** [xenobot-dev/apriltags_ros#1]
[ WARN] [1499245266.498581085]: Warning: Camera intrinsic matrix K is not set, can't recover 3D pose
[apriltags-1] process has died [pid 6676, exit code -11, cmd /home/khaled/apriltags_ros/apriltags_ws/devel/lib/apriltags/apriltags ~image:=/usb_cam/image_raw ~camera_info:=/usb_cam/camera_info ~marker_array:=/apriltags/marker_array ~detections:=/apriltags/detections __name:=apriltags __log:=/home/khaled/.ros/log/b42bb8b6-615c-11e7-ba0c-28e34736aaaf/apriltags-1.log].
log file: /home/khaled/.ros/log/b42bb8b6-615c-11e7-ba0c-28e34736aaaf/apriltags-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by YuehChuan** [comment]
Hi @khaledMaen , thanks for the issue. 
Did you do the intrinsic calibration in advance?
Pleaswe follow the step here or here
http://wiki.ros.org/camera_calibration/Tutorials/MonocularCalibration
https://github.com/mocap-tools/raspicam_node
then you well get an .yaml like mine is *head_camera.yaml*
substitute the file under path *~/apriltags_ws/src/usb_cam/camera_info/head_camera.yaml*https://github.com/xenobot-dev/apriltags_ros/blob/master/apriltags_ws/src/usb_cam/camera_info/head_camera.yaml

By the way, I'm using PS3 eye camera. I guess you are using some kind of  fisheye cam or with different resolution.  After you complete steps above, the issue would be  solved. Feel free to contact.

**Comment by YuehChuan** [comment]
no further  action, close for now. please feel free to reopen.
