### ISSUE TITLE
apriltags crashing with opencv 3.3.1

### ISSUE THREAD

**Issue by SietseAchterop** [xenobot-dev/apriltags_ros#2]
Hello,

Since the latest update in ROS/kinetic when opencv went from 3.2 to 3.3.1 apriltags crashes with an exception. 
Using ./gltest I get:
`OpenCV Error: Assertion failed (!fixedType() || ((Mat*)obj)->type() == mtype) in create, file /home/sietse/ROS/ws/opencv/modules/core/src/matrix.cpp, line 2428`

Using ./camtest I get NO errors.

Using `usb_cam_apriltags.launch` I get:
`[ WARN] [1514122268.882526201]: Warning: Camera intrinsic matrix K is not set, can't recover 3D pose

[apriltags-1] process has died [pid 23801, exit code -11, cmd /home/sietse/ROS/ws/devel/lib/apriltags/apriltags ~image:=/usb_cam/image_raw ~camera_info:=/usb_cam/camera_info ~marker_array:=/apriltags/marker_array ~detections:=/apriltags/detections __name:=apriltags __log:=/home/sietse/.ros/log/947e4fa4-e8ae-11e7-b7fe-ac220b1a4c95/apriltags-1.log].`

This mostly when a tags seems to be detected.
Has something been changed in opencv? Any pointer?
Thanks in advance,
    Sietse

**Comment by YuehChuan** [comment]
@SietseAchterop  Thanks for opening this issue! I'll test it as soon as possible!

**Comment by goldflower** [comment]
Hi, 

I bumped into a similar situation when I using "gazebo_cam_apriltags.launch".

I get
 
`OpenCV Error: Assertion failed (mtype == type0 || (((((mtype) & ((512 - 1) << 3)) >> 3) + 1) == 1 && ((1 << type0) & fixedDepthMask) != 0)) in create, file /tmp/binarydeb/ros-kinetic-opencv3-3.3.1/modules/core/src/matrix.cpp, line 2542
`
when any apriltag has been detected.

I'm not sure if I should open a new issue about this, if so, please let me know.

Thank you very much!

**Comment by SietseAchterop** [comment]
Hello YuehChuan,
have you been able to make any progress yet?

**Comment by SietseAchterop** [comment]
I now realise that there are 2 different C++-ports of apriltags. The one used here is another than the one used by ROS itself.
Please see

https://answers.ros.org/question/277859/ros-kinetic-opencv3-and-apriltags-regression/

for my question, answer and solution there!

**Comment by ChunJyeBehBeh** [comment]
May I know the link of the package that yall install and the command needed? I m a newbiee to ROS ...

**Comment by ChunJyeBehBeh** [comment]
May I know where the Matrix33d that I should change in this package? What is the file name?

**Comment by YuehChuan** [comment]
@SietseAchterop  Thanks for your effort!  Already fix!
@goldflower @ChunJyeBehBeh  Please try it.
https://github.com/xenobot-dev/apriltags_ros/commit/7a8eede37c96fe502aaee9c3c068ac5407239841
I will close the issue for now. feel free to reopen it.
