### ISSUE TITLE
WARNING: NEW QUAD ALGORITHM REQUESTED, BUT COMPILED WITHOUT CGAL SUPPORT, FALLING BACK TO OLD ALGORITHM.

### ISSUE THREAD

**Issue by SonOfCoding** [xenobot-dev/apriltags_ros#3]
I run the code, but there is no pose information. one terminal says WARNING: NEW QUAD ALGORITHM REQUESTED, BUT COMPILED WITHOUT CGAL SUPPORT, FALLING BACK TO OLD ALGORITHM.

One terminal outputs this:

header: 
  seq: 5996
  stamp: 
    secs: 1550839569
    nsecs: 241118043
  frame_id: "usb_cam"
detections: []
---
header: 
  seq: 5997
  stamp: 
    secs: 1550839569
    nsecs: 309614466
  frame_id: "usb_cam"
detections: []
---

I have installed CGAL package, what is the problem? can you help me ? thank you

**Comment by YuehChuan** [comment]
Try to remove all binaries and recompile.

**Comment by SonOfCoding** [comment]
I try to recompile and i still cannot get the pose information. The output of the terminal is shown below,

![screenshot from 2019-02-24 15-30-50](https://user-images.githubusercontent.com/43914081/53296412-8ebc8b80-3849-11e9-9a40-6d4a522ce330.png)

could you please give me a help? by the way, do you have qq or some other contact methods?

**Comment by YuehChuan** [comment]
The original issue 
WARNING: NEW QUAD ALGORITHM REQUESTED, BUT COMPILED WITHOUT CGAL SUPPORT, FALLING BACK TO OLD ALGORITHM.
solved.
 Could you print the aprilTags below first?  The raw camera stream looks strange.   
https://github.com/xenobot-dev/apriltags_ros/blob/master/software/tag36h11.pdf
